site_name: alGolang Documentation
site_uri: '/<l>/'
theme:
  name: null
  custom_dir: 'theme'
meta:
  lang: 'en'
languages:
  - lang: 'en'
    lang_name: 'English'
navigation:
  - title: 'Home'
    url: '/<l>/'
  - title: 'About'
    url: '/<l>/about/'
  - title: 'Algorithms'
    url: '/<l>/algorithms/'
  - title: 'Data Structures'
    url: '/<l>/data-structures/'

